apiVersion: v1
kind: Service
metadata:
    name: "menuitemkuber-0c94"
    labels:
        app: "menuitemkuber-0c94"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "menuitemkuber-0c94"