on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: menukubernetes.azurecr.io
        username: ${{ secrets.acr_menukubernetes_username }}
        password: ${{ secrets.acr_menukubernetes_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t menukubernetes.azurecr.io/menuitemkuber:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push menukubernetes.azurecr.io/menuitemkuber:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_menuitemkuber_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep menuitemkuber8730 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace menuitemkuber8730`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: menuitemkuber8730
        container-registry-url: menukubernetes.azurecr.io
        container-registry-username: ${{ secrets.acr_menukubernetes_username }}
        container-registry-password: ${{ secrets.acr_menukubernetes_password }}
        secret-name: menuitemkubedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: menuitemkuber8730
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          menukubernetes.azurecr.io/menuitemkuber:${{ github.sha }}
        imagepullsecrets: |
          menuitemkubedockerauth
